YEDEK9/MvcProjeKampi/Controllers/UserPanelController.cs
using BusinessLayer.Conctrete;
using BusinessLayer.ValidationRules;
using DataAccesLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class UserPanelController : Controller
    {

        UserManager um = new UserManager(new EFUserDal());
        CATEGORYManager cm = new CATEGORYManager(new EFCATEGORYDal());
        PRODUCTManager pm = new PRODUCTManager(new EFPRODUCTDal());
        PROPERTYManager pp = new PROPERTYManager(new EFPROPERTYDal());
        PRODUCTPROPERTYManager ppm = new PRODUCTPROPERTYManager(new EFPRODUCTPROPERTYDal());



        public User SessionValue()
        {
            string p;
            p = (string)Session["USERNAME"];
            var UserValue = um.GetSessionValue(p);
            return UserValue;
        }

    



        [HttpGet]
        public ActionResult MenuCategoryAdd()
        {

            return View();
        }
        [HttpPost]
        public ActionResult MenuCategoryAdd(CATEGORY cat)
        {

            cat.CREATORUSERID = SessionValue().USERID;


            Random randm = new Random();

     

            if (Request.Files.Count > 0)
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                if (filename == "")
                {
                    cat.CATEGORYIMAGE = "/Extra/images/fooddef.png";
                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));


                        cat.CATEGORYIMAGE = "/ımage/" + filename + rdn + uzanti;


                    }
                }


            }

            DateTime dt = DateTime.Parse(DateTime.Now.ToLongDateString());
            cat.CREATEDDATE = dt;

            CategoryValidatior cv = new CategoryValidatior();
            ValidationResult results = cv.Validate(cat);
            if (results.IsValid)
            {
                cm.AddValue(cat);
                TempData["AlertMessage1"] = "Menü Kategoriniz Eklendi.";
                return RedirectToAction("MenuCategoryAdd");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }

                return View();
            }


          


            
           
        }


        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {


            var catupdatevalue = cm.GetByID(id);


            return View(catupdatevalue);
        }

        [HttpPost]
        public ActionResult UpdateCategory(CATEGORY value)
        {


            Random randm = new Random();

            var valueforupdate = cm.GetByID(value.CATEGORYID);

            if (Request.Files.Count > 0 || Request.PathInfo != "")
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                if (filename == "")
                {


                    string valueımage = valueforupdate.CATEGORYIMAGE;

                    value.CATEGORYIMAGE = valueımage;

                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));


                        value.CATEGORYIMAGE = "/ımage/" + filename + rdn + uzanti;


                    }
                }


            }




            var valueid = valueforupdate.CATEGORYID;

            value.CREATEDDATE = DateTime.Parse(DateTime.Now.ToLongTimeString());


            CategoryValidatior cv = new CategoryValidatior();
            ValidationResult results = cv.Validate(value);
            if (results.IsValid)
            {
                cm.CategoryUpdate(value, valueid);
                TempData["AlertMessage3"] = "Seçilen Kategori Güncellendi.";
            
                return RedirectToAction("SeeMenuCategories");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);

                }

                return View(valueforupdate);
            }

       

         

      
           
        }




        public ActionResult SeeMenuCategories()
        {
            ViewBag.uservalue = SessionValue();

            var ListCategories = cm.GetList();

            return View(ListCategories);
        }


        public ActionResult SeeMenuList()
        {
            ViewBag.uservalue = SessionValue();

            var ListCategories = cm.GetByUserID(SessionValue().USERID);

            return View(ListCategories);
        }

 

        public ActionResult EditMenuContent(int id)
        {


            var ListValue = ppm.GetListCategory(id);

            return View(ListValue);
        }

        [HttpGet]
        public ActionResult EditMenuContentPage(int id)
        {

            var value = pm.GetByIDProduct(id);


            return View(value);
        }

        [HttpPost]
        public ActionResult EditMenuContentPage(PRODUCT p)
        {

            Random randm = new Random();

            if (Request.Files.Count > 0 || Request.PathInfo != "")
            {
                string rdn = Convert.ToString(randm.Next(0, 9999));
                string filename = Path.GetFileName(Request.Files[0].FileName);
                string uzanti = Path.GetExtension(Request.Files[0].FileName);
                string yol = "~/ımage/" + filename + rdn + uzanti;

                var getvalue = cm.GetByID(p.CATEGORYID);
                if (filename == "")
                {


                    string valueımage = getvalue.CATEGORYIMAGE;

                    p.IMAGEPATH = valueımage;

                }
                else
                {
                    if (yol == "~/ımage/")
                    {

                    }
                    else
                    {

                        Request.Files[0].SaveAs(Server.MapPath(yol));


                        p.IMAGEPATH = "/ımage/" + filename + rdn + uzanti;


                    }
                }


            }

            p.CREATEDDATE = DateTime.Parse(DateTime.Now.ToLongTimeString());

            pm.PRODUCTUpdate(p);
            
           
            return RedirectToAction("UpdateProp", new { id = p.PRODUCTID });
        }

        [HttpGet]
        public ActionResult UpdateProp(int id)
        {
            var value = ppm.GetProp(id);
            return View(value);
        }

        [HttpPost]
        public ActionResult UpdateProp(PROPERTY P)
        {



            var forıd = pm.GetByIDProduct(P.KEY);

          

            pp.PROPERTYUpdate(P);

            var updatePp = ppm.GetProp(P.KEY);

            updatePp.PRODUCTID = P.KEY;
            updatePp.PROPERTYID = P.PROPERTYID;

            ppm.PRODUCTPROPERTYUpdate(updatePp);
            TempData["AlertMessageContent001"] = "Ürün Güncellendi.";
            return RedirectToAction("EditMenuContent", new { id = forıd.CATEGORYID });

        }


        public ActionResult DeleteMenuContent(int id)
        {
            var value = pm.GetByIDProduct(id);
            value.ISDELETED = true;

            pm.PRODUCTUpdate(value);

            TempData["AlertMessageDelete"] = "Seçilen İçerik Silindi.";
            return RedirectToAction("EditMenuContent", new { id = value.CATEGORYID });
        }


       

        public ActionResult DeleteCategory(int id)
        {


            var catdeletevalue = cm.GetByID(id);
            catdeletevalue.ISDELETED = true;
            cm.CategoryUpdate(catdeletevalue, catdeletevalue.CATEGORYID);
            TempData["AlertMessage1"] = "Seçilen Kategori Silindi.";
            return RedirectToAction("SeeMenuCategories");
        }





        [HttpGet]
        public ActionResult AddProp(int id)
        {
            var value = pm.GetByIDProduct(id);
            return View(value);
        }

        [HttpPost]
        public ActionResult AddProp(PROPERTY P)
        {



            var forıd = pm.GetByIDProduct(P.KEY);

            pp.AddValue(P);

            PRODUCTPROPERTY ppForAdd = new PRODUCTPROPERTY();
            ppForAdd.PRODUCTID = P.KEY;
            ppForAdd.PROPERTYID = P.PROPERTYID;
            ppm.AddValue(ppForAdd);
            TempData["AlertMessageContent01"] = "Yeni Ürün Eklendi.";
            return RedirectToAction("AddContent", new { id = forıd.CATEGORYID });

        }



        [HttpGet]
        public ActionResult AddContent(int id)
        {
            var value = cm.GetByID(id);


            return View(value);




        }






        [HttpPost]
        public ActionResult AddContent(PRODUCT p)
        {

            try
            {

                Random randm = new Random();



                if (Request.Files.Count > 0 || Request.PathInfo != "")
                {
                    string rdn = Convert.ToString(randm.Next(0, 9999));
                    string filename = Path.GetFileName(Request.Files[0].FileName);
                    string uzanti = Path.GetExtension(Request.Files[0].FileName);

YEDEK9/MvcProjeKampi/Views/UserPanel/AddContent.cshtml
@model EntityLayer.Concrete.CATEGORY

@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}


<!DOCTYPE html>

<style>
    .avatar {
        vertical-align: middle;
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }
</style>
<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->


<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/Web2/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Account settings - Account | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/Web2/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="../assets/js/config.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                       
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <!-- Place this tag where you want the button to render. -->
                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">


                             
                                    <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                        <div class="avatar avatar-online">
                                            <img src="~/Extra/images/fre2.png" alt="Avatar" class="avatar" />


                                        </div>
                                    </a>

                            
                         



                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">

                        <div class="row">
                            <div class="col-md-12">
                                @if (TempData["AlertMessageContent01"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color: blueviolet"> Başarılı ! @TempData["AlertMessageContent01"] </strong>
                                    </div>

                                }

                                @if (TempData["AlertMessageContent2"] != null)
                                {<div class="alert alert-info ">
                                        <strong class="text-center" style="color: blueviolet"> Başarısız ! @TempData["AlertMessageContent2"] </strong>
                                    </div>

                                }
                                <BR />
                                <div class="card mb-4">

                                    <!-- Account -->
                                    <BR />

                                    @using (Html.BeginForm("AddContent", "UserPanel", FormMethod.Post, new { enctype = "multipart/form-data" }))
                                    {
                                        <div class="card-body">
                                            <div class="d-flex align-items-start align-items-sm-center gap-4">
                                                <img src="@Model.CATEGORYIMAGE"
                                                     alt="user-avatar"
                                                     class="d-block rounded"
                                                     height="180"
                                                     width="180"
                                                     id="uploadedAvatar" />
                                                <div class="button-wrapper">
                                                    <label for="upload" class="btn btn-primary me-2 mb-4" tabindex="0">
                                                        <span class="d-none d-sm-block">Fotoğraf Yükle</span>
                                                        <i class="bx bx-upload d-block d-sm-none"></i>
                                                        <input type="file"
                                                               id="upload"
                                                               name="IMAGEPATH"
                                                               class="account-file-input"
                                                               hidden
                                                               accept="image/png, image/jpeg" />
                                                    </label>


                                                    <p class="text-muted mb-0">Yanlızca Jpg ve Png formatında yükleme yapınız. </p>
                                                </div>
                                            </div>
                                        </div>
                                        <hr class="my-0" />
                                        <div class="card-body">

                                            <div class="row">
                                                <div class="mb-3 col-md-6">
                                                    <label for="firstName" class="form-label">Ürün Adı</label>
                                                    <input class="form-control"
                                                           type="text"
                                                           id=""
                                                           name="PRODUCNAME"
                                                           placeholder="Fincan Çay vs.."
                                                           autofocus />

                                                
                                                </div>




                                                <div class="mb-3 col-md-6">
                                                    <label for="organization" class="form-label">Ürün Fiyatı</label>
                                                    <input type="text"
                                                           class="form-control"
                                                           id="organization"
                                                           name="PRICE"
                                                           placeholder="10 $" />
                                                </div>



                                                <div class="mb-3 col-md-6">
                                                    <label for="zipCode" class="form-label">Eklenceği Kategori</label>
                                                    <input class="form-control"
                                                           id="zipCode"
                                                           placeholder="@Model.CATEGORYNAME"
                                                           name=""
                                                           disabled />
                                                </div>

                                                <input type="hidden" value="@Model.CATEGORYID" name="CATEGORYID" />



                                                <div class="mb-3 col-md-6">


                                                </div>
                                                <div class="mb-3 col-md-6">

                                                </div>


                                            </div>
                                            <div class="mt-2">
                                                <button type="submit" class="btn btn-primary me-2">Değişiklikleri Kaydet</button>

                                                <a href="/UserPanel/SeeMenuCategories" class="btn btn-outline-secondary">Vazgeç</a>
                                            </div>



                                        </div>
                                    }
                                    <!-- /Account -->
                                </div>

                            </div>

                        </div>
                    </div>


                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->

       

    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/Web2/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/Web2/assets/js/pages-account-settings-account.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>

YEDEK9/MvcProjeKampi/Views/UserPanel/AddProp.cshtml
@model EntityLayer.Concrete.PRODUCT


@{
    ViewBag.Title = "AddProp";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<!DOCTYPE html>

<style>
    .avatar {
        vertical-align: middle;
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }
</style>
<!-- =========================================================
* Sneat - Bootstrap 5 HTML Admin Template - Pro | v1.0.0
==============================================================

* Product Page: https://themeselection.com/products/sneat-bootstrap-html-admin-template/
* Created by: ThemeSelection
* License: You must have a valid license purchased in order to legally use the theme for your project.
* Copyright ThemeSelection (https://themeselection.com)

=========================================================
 -->
<!-- beautify ignore:start -->


<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-assets-path="~/Web2/assets/"
      data-template="vertical-menu-template-free">
<head>
    <meta charset="utf-8" />
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0" />

    <title>Account settings - Account | Sneat - Bootstrap 5 HTML Admin Template - Pro</title>

    <meta name="description" content="" />

    <!-- Favicon -->
    <link rel="icon" type="image/x-icon" href="../assets/img/favicon/favicon.ico" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/Web2/assets/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/Web2/assets/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/Web2/assets/vendor/js/helpers.js"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="../assets/js/config.js"></script>
</head>

<body>
    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">
                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0)">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">
                        <!-- Search -->
                        <!-- /Search -->

                        <ul class="navbar-nav flex-row align-items-center ms-auto">
                            <!-- Place this tag where you want the button to render. -->
                            <!-- User -->
                            <li class="nav-item navbar-dropdown dropdown-user dropdown">



                                <a class="nav-link dropdown-toggle hide-arrow" href="javascript:void(0);" data-bs-toggle="dropdown">
                                    <div class="avatar avatar-online">
                                        <img src="~/Extra/images/fre2.png" alt="Avatar" class="avatar" />


                                    </div>
                                </a>






                            </li>
                            <!--/ User -->
                        </ul>
                    </div>
                </nav>

                <!-- / Navbar -->
                <!-- Content wrapper -->
                <div class="content-wrapper">
                    <!-- Content -->

                    <div class="container-xxl flex-grow-1 container-p-y">

                        <div class="row">
                            <div class="col-md-12">

                                <BR />
                                <div class="card mb-4">

                                    <!-- Account -->
                                    <BR />

                                    @using (Html.BeginForm("AddProp", "UserPanel", FormMethod.Post))
                                    {

                                        <div class="card-body">

                                            <div class="row">





                                                <div class="mb-3 col-md-6">
                                                    <label for="organization" class="form-label">Ürün Özellik</label>
                                                    <input type="text"
                                                           class="form-control"
                                                           id="organization"
                                                           name="VALUE"
                                                           placeholder=" Bol malzemelidir vs.. " />
                                                </div>



                                                <div class="mb-3 col-md-6">
                                                    <label for="zipCode" class="form-label">Eklenceği Ürün</label>
                                                    <input class="form-control"
                                                           id="zipCode"
                                                           placeholder="@Model.PRODUCNAME"
                                                           name=""
                                                           disabled />
                                                </div>

                                                <input type="hidden" value="@Model.PRODUCTID" name="KEY" />



                                                <div class="mb-3 col-md-6">


                                                </div>
                                                <div class="mb-3 col-md-6">

                                                </div>


                                            </div>
                                            <div class="mt-2">
                                                <button type="submit" class="btn btn-primary me-2">Değişiklikleri Kaydet</button>

                                                <a href="/UserPanel/SeeMenuCategories" class="btn btn-outline-secondary">Vazgeç</a>
                                            </div>



                                        </div>
                                    }
                                    <!-- /Account -->
                                </div>

                            </div>

                        </div>
                    </div>


                </div>
                <!-- Content wrapper -->
            </div>
            <!-- / Layout page -->
        </div>

        <!-- Overlay -->



    </div>
    <!-- / Layout wrapper -->
    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/Web2/assets/vendor/libs/jquery/jquery.js"></script>
    <script src="~/Web2/assets/vendor/libs/popper/popper.js"></script>
    <script src="~/Web2/assets/vendor/js/bootstrap.js"></script>
    <script src="~/Web2/assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/Web2/assets/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <!-- Main JS -->
    <script src="~/Web2/assets/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/Web2/assets/js/pages-account-settings-account.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
</body>
</html>